# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 74f26f470c5e21702af6b3de8f41e6a0938048f99dc270208167d00240580aff525140b2a6c55664268c3e1092f1611c456e163e0ffca42bb026a5615b858d3e

test:
  secret_key_base: 953937a5d0a62f82741c3e7d61dab6255e8f464c3c8ca0bbd201641a0ca6bdacf667583b3bbeeb77b133c0b5b5bf03405883bcae7c28bb0579b8bc28d5627342

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
